SDAP-304 : Added optional domsconfig "create_keyspace_granted"
apache/incubator-sdap-nexus pull request #125
Opened 2021-03-26 13:11 UTC by twnone

Value can be : True [default] / False
Admin must setup the value to False if the Cassandra user has restricted permissions on the cluster.

The value will be checked before creating DOMS keyspace.
If the user is not permitted to create a keyspace on the Cassandra cluster, then the keyspace will be directly selected & the tables will be created (if needed).

Tested by dropping an existing table ; when Nexus starts, the table is correctly created.

2021-04-08 19:21 UTC, skorper requested changes

2021-04-08 19:21 UTC, skorper commented on analysis/webservice/algorithms/doms/DomsInitialization.py
> +        except NoOptionError:
@twnone This line caused errors when running my test, but seemed to work when I changed it to

```suggestion
        except configparser.NoOptionError:
```

2021-04-09 09:45 UTC, twnone commented
@skorper You are right, the exception processing was not correctly tested on my side ; a lesson was learned here. The issue should be fixed in my last commits.

2021-04-16 05:11 UTC, skorper approved these changes

2021-04-16 23:31 UTC, ngachung approved these changes

2021-04-16 23:34 UTC, merged